prefeiturasp/SME-Conecta-Formacao

- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
> Fix/101255 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoUsuarioAlterarSenha.cs
- SME.ConectaFormacao.Dominio/Extensoes/JsonExtensao.cs
[AB#101356](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/101356)
> Fix/101356 para Release

- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
- SME.ConectaFormacao.TesteIntegracao/Usuario/Ao_Alterar_senha_do_usuario.cs
- SME.ConectaFormacao.TesteIntegracao/Usuario/Ao_alterar_email_do_usuario.cs
- SME.ConectaFormacao.TesteIntegracao/Usuario/Ao_recuperar_senha_do_usuario.cs
[AB#101822](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/101822)
> Fix/101822 para Release

- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaCriterioValidacaoInscricao.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaFuncaoEspecifica.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaPublicoAlvo.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaVagaRemanecente.cs
- SME.ConectaFormacao.Dominio/Enumerados/Modalidade.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoFormacao.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoIscricao.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaCriterioValidacaoInscricaoMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaFuncaoEspecificaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaPublicoAlvoMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaVagaRemanecenteMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- scripts/V6__CRIACAO_TABELA_PROPOSTA.sql
[AB#101860](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/101860)
> Feature/101860 para Story

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterTipoInscricao.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTipoInscricao/ObterTipoInscricaoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTipoInscricao/ObterTipoInscricaoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterTipoInscricao.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoInscricao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_tipo_inscricao.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#101894](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/101894)
> Criando o endpoint de tipo inscrição

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
[AB#103127](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/103127)
[AB#102991](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/102991)
> Fix/103127 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterModalidades.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterModalidades/ObterModalidadesQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterModalidades/ObterModalidadesQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterModalidades.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_modalidades.cs
- SME.ConectaFormacao.Webapi/Contexto/ContextoHttp.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#103261](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/103261)
> Fix/103261 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/AreaPromotora/CasoDeUsoObterAreaPromotoraLista.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraLista/ObterAreaPromotoraListaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraLista/ObterAreaPromotoraListaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/AreaPromotora/ICasoDeUsoObterAreaPromotoraLista.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioAreaPromotora.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/AreaPromotora/Ao_obter_lista_area_promotora.cs
- SME.ConectaFormacao.Webapi/Controllers/AreaPromotoraController.cs
[AB#101934](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/101934)
> Feature/101934 para Story

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterComunicadoComunicadoAcaoFormativa.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ParametrosSistema/ObterParametroSistemaPorTipoEAnoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ParametrosSistema/ObterParametroSistemaPorTipoEAnoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/ComunicadoAcaoFormativaDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterComunicadoAcaoFormativa.cs
- SME.ConectaFormacao.Dominio/Entidades/ParametroSistema.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoParametroSistema.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/ParametroSistemaMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioParametroSistema.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioParametroSistema.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_comunicado_acao_formativa.cs
- SME.ConectaFormacao.TesteIntegracao/Queries/Ao_recuperar_parametro_sistema.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
- SME.ConectaFormacao.Webapi/SME.ConectaFormacao.Webapi.csproj
- scripts/V16__CRIACAO_TABELA_PARAMETRO_SISTEMA.sql
[AB#105687](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/105687)
> Criar Endpoint ou parâmetro para retornar Numero/Data/Link do Comunicado

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaRegentePaginacao.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterRegentesPaginado/ObterRegentesPaginadoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterRegentesPaginado/ObterRegentesPaginadoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterPropostaRegentePaginacao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#105679](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/105679)
> Criado endpoint de regente paginado

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaRegentePorId.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterRegentePorId/ObterRegentePorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterRegentePorId/ObterRegentePorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterRegenteTurmaPorRegenteId/ObterRegenteTurmaPorRegenteIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterRegenteTurmaPorRegenteId/ObterRegenteTurmaPorRegenteIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterPropostaRegentePorId.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#105673](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/105673)
>  Criar Endpoint de Obter Regente Por Id

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoRemoverPropostaTutor.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/RemoverPropostaTutor/RemoverPropostaTutorCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/RemoverPropostaTutor/RemoverPropostaTutorCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoRemoverPropostaTutor.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#105678](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/105678)
> Criando endpoint de excluir tutor

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaRegentePorId.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaTutorPorId.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorPorId/ObterTutorPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorPorId/ObterTutorPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorTurmaPorTutorId/ObterTutorTurmaPorTutorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorTurmaPorTutorId/ObterTutorTurmaPorTutorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterPropostaTutorPorId.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#105676](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/105676)
> Endpoint de Obter Tutor Por Id

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterNomeRegenteTutor.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaTutorPaginacao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaTutorPorId.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoRemoverPropostaRegente.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoRemoverPropostaTutor.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoSalvarPropostaRegente.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoSalvarPropostaTutor.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/RemoverPropostaRegente/RemoverPropostaRegenteCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/RemoverPropostaRegente/RemoverPropostaRegenteCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/RemoverPropostaTutor/RemoverPropostaTutorCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/RemoverPropostaTutor/RemoverPropostaTutorCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaRegente/SalvarPropostaRegenteCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaRegente/SalvarPropostaRegenteCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTutor/SalvarPropostaTutorCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTutor/SalvarPropostaTutorCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterNomeProfissionalPorRegistroFuncional/ObterNomeProfissionalPorRegistroFuncionalQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterNomeProfissionalPorRegistroFuncional/ObterNomeProfissionalPorRegistroFuncionalQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorPaginado/ObterTutorPaginadoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorPaginado/ObterTutorPaginadoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorPorId/ObterTutorPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorPorId/ObterTutorPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorTurmaPorTutorId/ObterTutorTurmaPorTutorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTutorTurmaPorTutorId/ObterTutorTurmaPorTutorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaRegenteDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTutorDTO.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/ServicosFakes/ObterNomeProfissionalPorRegistroFuncionalQueryHandlerFake.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/ao_obter_nome_profissional.cs
[AB#107766](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/107766)
[AB#107753](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/107753)
> Ajuste de namespace

- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
[AB#107765](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/107765)
[AB#107769](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/107769)
> Corrreção bug

- SME.ConectaFormacao.Dominio/Entidades/PropostaRegente.cs
- scripts/V20__ALTERAR_TABELA_REGENTE.sql
[AB#107753](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/107753)
> Minibiografia aceitando null

- SME.ConectaFormacao.Aplicacao/Dtos/Grupo/GrupoDTO.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/AcessosGrupo.cs
[AB#105691](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/105691)
> Adicionado VisaoId no retorno do endpoint de grupos

- SME.ConectaFormacao.Aplicacao/CasosDeUso/AreaPromotora/CasoDeUsoObterAreaPromotoraPorId.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraPorId/ObterAreaPromotoraPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterGrupoPorId/ObterGrupoPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterGrupoPorId/ObterGrupoPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/AreaPromotora/AreaPromotoraCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/SME.ConectaFormacao.Aplicacao.csproj
- SME.ConectaFormacao.Infra.Servicos/Acessos/Interfaces/IServicoAcessos.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
[AB#108374](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/108374)
> Obter grupo

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaPaginada/ObterPropostaPaginadaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaFiltrosDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaPaginadaDTO.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- scripts/V24__ADD_CAMPO_FORMACAO_HOMOLOGADA_TABELA_PROPOSTA.sql
[AB#108511](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/108511)
> [Back] Adicionar Formação Homologada na Entidade Proposta

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#109159](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109159)
[AB#109185](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109185)
> Correção na validação de quantidade de encontros

- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
[AB#108514](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/108514)
> [Back] Alterar Enum de Situação Proposta

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarDetalhamentoDaProposta/ValidarDetalhamentoDaPropostaCommandHandler.cs
[AB#109175](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109175)
> Ajuste em validações ao salvar proposta

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarPropostaParaDf.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarCertificacaoProposta/ValidarCertificacaoPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarEncontrosProfissionaisAoEnviarDf/ValidarEncontrosProfissionaisAoEnviarDfCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarEncontrosProfissionaisAoEnviarDf/ValidarEncontrosProfissionaisAoEnviarDfCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarInformacoesGerais/ValidarInformacoesGeraisCommandHandler.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_enviar_proposta_para_df.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#109171](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109171)
> BACK - Correção na validação de quantidade de encontros

- SME.ConectaFormacao.Dominio/Enumerados/Permissao.cs
[AB#108975](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/108975)
> [Back] Criar permissão no coresso - parecer

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterFormacaoHomologada.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterFormacaoHomologada/ObterFormacaoHomologadaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterFormacaoHomologada/ObterFormacaoHomologadaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterFormacaoHomologada.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Dominio/Enumerados/FormacaoHomologada.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_formacao_homologada.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
- scripts/V30__ALTERAR_TABELA_PROPOSTA_TIPO_FORMACAO_HOMOLOGADA.sql
[AB#109877](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109877)
> Feature/109877 para Story/109646

- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTurma.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaMap.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- scripts/V34__CRIAR_TABELA_PROPOSTA_TURMA.sql
[AB#109891](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109891)
> Feature/109891 para Story/109646

- SME.ConectaFormacao.Dominio/Enumerados/LogContexto.cs
- SME.ConectaFormacao.Infra.Servicos/CacheDistribuido/CacheDistribuido.cs
- SME.ConectaFormacao.Infra.Servicos/CacheDistribuido/CacheDistribuidoRedis.cs
- SME.ConectaFormacao.Infra.Servicos/CacheDistribuido/ICacheDistribuido.cs
- SME.ConectaFormacao.Infra.Servicos/CacheDistribuido/IoC/CacheDistribuidoRedisCHelper.cs
- SME.ConectaFormacao.Infra.Servicos/CacheDistribuido/Opcoes/CacheDistribuidoRedisOpcao.cs
- SME.ConectaFormacao.Infra.Servicos/SME.ConectaFormacao.Infra.Servicos.csproj
- SME.ConectaFormacao.Infra.Servicos/Utilitarios/Gzip.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
[AB#108513](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/108513)
> Feature/108513 para story/107855

- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTurmaDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTurma.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#110744](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110744)
> feature/110744 para Story/109646

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Dre/CasoDeUsoObterListaDre.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarPropostaRascunho/AlterarPropostaRascunhoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirProposta/InserirPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirPropostaRascunho/InserirPropostaRascunhoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurma/SalvarPropostaTurmaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurmaDre/SalvarPropostaTurmaDreCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurmaDre/SalvarPropostaTurmaDreCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarCriterioValidacaoInscricaoOutros/ValidarCriterioValidacaoInscricaoOutrosCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Dre/DreDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTurmaDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTurmaDreDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Dre/ICasoDeUsoObterListaDre.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTurma.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTurmaDre.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaDreMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_inserir_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- scripts/V38__CRIAR_TABELA_PROPOSTA_TURMA_DRE.sql
[AB#110780](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110780)
> [Backend] - A proposta turma permitirá multiplas DREs

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#110200](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110200)
> Fix/110200 para Release

- SME.ConectaFormacao.Dominio/Entidades/Inscricao.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/InscricaoMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/UsuarioMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- scripts/V39__CRIAR_TABELA_INSCRICAO.sql
[AB#110054](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110054)
> Feature/110054 para Story/107936

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoCancelarInscricao.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/CancelarInscricao/CancelarInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/CancelarInscricao/CancelarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoCancelarInscricao.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_cancelar_inscricao.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/InscricaoMock.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#110064](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110064)
> Task 110064: [BACK] Endpoint de Cancelar Inscrição do cursista

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterTurmasInscricao.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTurmasComVagasPorId/ObterPropostaTurmasComVagasPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTurmasComVagasPorId/ObterPropostaTurmasComVagasPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterTurmasInscricao.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/InscricaoMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_turmas_com_vaga.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#110059](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110059)
> Feature/110059 para Story/107936

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoDTO.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/InscricaoMap.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_enviar_inscricao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/DreMock.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#111709](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/111709)
> Feature/111709 - Complementação

- SME.ConectaFormacao.Aplicacao/CasosDeUso/AreaPromotora/CasoDeUsoObterAreaPromotoraPaginada.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/CasoDeUsoAbstratoPaginado.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterInscricaoPaginada.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterListagemFormacaoPaginado.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaEncontroPaginacao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaPaginacao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaRegentePaginacao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaTutorPaginacao.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPaginadaPorUsuarioIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPaginadaPorUsuarioIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoPaginadaDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterInscricaoPaginada.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/Inscricao.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTurma.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_inscricoes_paginada.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/InscricaoMock.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#110062](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110062)
> Feature/110062 para Story/107936

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosInscricao.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/DadosInscricaoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoDTO.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Dto/CargoFuncionarioConectaDTO.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_enviar_inscricao.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#111906](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/111906)
> Ajustando o tipo de dados dos campos de dre e ues

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
[AB#111828](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/111828)
> Correção no mapeamento do cargo função

- SME.ConectaFormacao.Dominio/Enumerados/Permissao.cs
[AB#110051](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110051)
> Ajustes no enum

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_enviar_inscricao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
[AB#111828](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/111828)
> Avaliação de cargo e função pelo código do eol

- SME.ConectaFormacao.Dominio/Enumerados/TipoInscricao.cs
[AB#109811](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109811)
> [BACK] - Adicionar tipo Automática (JEIF)

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosPaginadosComFiltros.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112348](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112348)
> Correções repasse

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/FiltroListagemInscricaoDTO.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112384](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112384)
> [BACK] Fix/112384

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112362](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112362)
> Paginação de Listagem por id

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112455](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112455)
> fix/112455 - Ajuste em consulta sql

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#112395](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112395)
> Correção de Permissão e Ordenação

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterInscricaoPorId.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112494](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112494)
> fix/112494 - Novas formações não são exibidas na listagem de formações

- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_inscricoes_por_id_e_filtro.cs
Correção em testes nos testes , após corre de bugs
> Correção em testes

- scripts/V43__ALTERAR_TABELA_PROPOSTA_TURMA.sql
[AB#112524](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112524)
> [BACK] - Limite de caracteres para o campo

- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/UsuarioPerfisRetornoDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/ServicoParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/AcessosPerfilUsuarioRetorno.cs
[AB#112404](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112404)
> obter cpf no login

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Dtos/Inscricao/ListagemFormacaoComTurmaDTO.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112672](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112672)
[AB#112767](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112767)
> Coluna Data - Ao realizar inscrições a coluna data é acrescenta data conforme inscrições realizadas

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
[AB#112662](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112662)
> Ajuste na contagem de paginas

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Formacao/CasoDeUsoObterListagemFormacaoPaginado.cs
[AB#111071](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/111071)
> fix/111071 para Release

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaPaginada/ObterPropostaPaginadaQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#112662](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112662)
> Correção na paginação da tela de Propostas

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112991](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112991)
> Formações do tipo "Automática" não estão sendo exibidas

- SME.ConectaFormacao.Dominio/Entidades/PropostaTipoInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTipoInscricaoMap.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- scripts/V39__CRIAR_TABELA_INSCRICAO.sql
- scripts/V45__CRIAR_TABELA_PROPOSTA_TIPO_INSCRICAO.sql
[AB#113036](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113036)
> Feature/113036 para Story/112515

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirProposta/InserirPropostaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTipoInscricao/SalvarPropostaTipoInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTipoInscricao/SalvarPropostaTipoInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarInformacoesGerais/ValidarInformacoesGeraisCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTipoInscricaoPorId/ObterPropostaTipoInscricaoPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTipoInscricaoPorId/ObterPropostaTipoInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTipoInscricaoDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTipoInscricaoMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_enviar_inscricao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Mocks/AoRealizarInscricaoAutomaticaMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_inserir_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#113039](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113039)
> Feature/113039 para Story/112515

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomaticaTratarCursista.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoAutomaticaDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
[AB#113298](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113298)
> Fix/113298 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomaticaTratarTurmas.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/CursistaServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Worker/WorkerRabbitConecta.cs
[AB#113308](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113308)
> Fix/113308 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomaticaTratarTurmas.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirPropostaTurmaEDre/InserirPropostaTurmaEDreCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirPropostaTurmaEDre/InserirPropostaTurmaEDreCommandHandler.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTurma.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#113355](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113355)
> Fix/113355 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterInscricaoPorId.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterInscricaoPorId.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#113418](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113418)
> Fix/113418 para Release

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#112662](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112662)
> Correção paginação Lista de inscrições

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#113465](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113465)
[AB#113876](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113876)
> Sistema permite publicar uma formação sem informar a DRE

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomaticaTratarTurmas.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoAutomatica/SalvarInscricaoAutomaticaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirPropostaTurmaEDre/InserirPropostaTurmaEDreCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirPropostaTurmaEDre/InserirPropostaTurmaEDreCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarInformacoesGerais/ValidarInformacoesGeraisCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoAutomaticaTratarTurmasDTO.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/ObjetosDeValor/PropostaInscricaoAutomatica.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_realizar_inscricao_automatica.cs
[AB#113043](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113043)
> Feature/113043 para Story/112515

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarSeDataInscricaoEhMaiorQueDataRealizacao/ValidarSeDataInscricaoEhMaiorQueDataRealizacaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarSeDataInscricaoEhMaiorQueDataRealizacao/ValidarSeDataInscricaoEhMaiorQueDataRealizacaoCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#113473](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113473)
> Sistema permite publicar uma formação com o Período de Inscrição maior que o Período de Realização

- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoCadastroUsuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoParametroSistema.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/UsuarioMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- scripts/V46__INSERIR_PARAMETRO_SISTEMA_DOMINIO_EMAIL.sql
- scripts/V47__ADICIONAR_CAMPOS_TABELA_USUARIO.SQL
[AB#109783](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109783)
> Adicionar campos tabela de usuario - domínio - repositório - mapeamento

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Ue/CasoDeUsoObterUePorCodigo.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterUePorCodigoEOL/ObterUePorCodigoEOLQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterUePorCodigoEOL/ObterUePorCodigoEOLQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Ue/ICasoDeUsoObterUePorCodigo.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Constante/ServicoEolConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Interfaces/IServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/UeServicoEol.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/UeController.cs
[AB#109786](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109786)
> Criar endpoint que pesquisa UE na API EOL por código

- SME.ConectaFormacao.Aplicacao/CasosDeUso/FuncionarioExterno/ObterFuncionarioExternoPorCpf/CasoDeUsoObterFuncionarioExternoPorCpf.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDadosFuncionarioExterno/ObterDadosFuncionarioExternoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDadosFuncionarioExterno/ObterDadosFuncionarioExternoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/FuncionarioExterno/ObterFuncionarioExternoPorCpf/ICasoDeUsoObterFuncionarioExternoPorCpf.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Constante/ServicoEolConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/FuncionarioExternoServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Interfaces/IServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/FuncionarioExternoController.cs
[AB#109798](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/109798)
> Criar endpoint para retornar dados usuário externo

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
- SME.ConectaFormacao.Dominio/ObjetosDeValor/PropostaInscricaoAutomatica.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#114362](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114362)
> Fix/114362 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomaticaTratarTurmas.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#113644](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113644)
> Fix/113644 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Autentiacao/CasoDeUsoAutenticarUsuario.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AtivarUsuarioExterno/AtivarUsuarioExternoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Usuario/ValidarUsuarioSituacaoAtiva/ValidarUsuarioSituacaoAtivaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Usuario/ValidarUsuarioSituacaoAtiva/ValidarUsuarioSituacaoAtivaQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
[AB#114392](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114392)
> BACK - Validar usuarios externos ativos no login

- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
[AB#114543](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114543)
[AB#114502](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114502)
> Correção do Erro de Obter Perfil no Primeiro acesso

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Formacao/CasoDeUsoObterListagemFormacaoPaginado.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdsPorFiltro/ObterPropostasIdsPorFiltroQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdsPorFiltro/ObterPropostasIdsPorFiltroQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#111131](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/111131)
> Fix/111131 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
[AB#114737](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114737)
> Fix/114737 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/UsuarioExternoDTO.cs
[AB#114491](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114491)
> Alterado Codigo ue para unidade e criado validação

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostasDashboard.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasDashboard/ObterPropostasDashboardQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasDashboard/ObterPropostasDashboardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdDashboard/ObterPropostasIdDashboardQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdDashboard/ObterPropostasIdDashboardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTotalDashboardPorTipo/ObterTotalDashboardPorTipoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTotalDashboardPorTipo/ObterTotalDashboardPorTipoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/CacheDistribuidoNomes.cs
- SME.ConectaFormacao.Infra.Dados/ConectaFormacaoConexao.cs
- SME.ConectaFormacao.Infra.Dados/Dtos/Dashboard/QuantidadeTipoDashboardDTO.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
[AB#115143](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115143)
> Ajuste de Performance consulta do Dashboard

- SME.ConectaFormacao.Aplicacao/Comandos/AreaPromotora/RemoverAreaPromotora/RemoverAreaPromotoraCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioAreaPromotora.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
[AB#114981](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114981)
> Fix/114981 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostasDashboard.cs
[AB#115268](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115268)
> Datas exibidas nos quadros está exibindo no formato mês/dia/ano

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaDetalhePorId/ObterFormacaoDetalhadaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/RetornoFormacaoDetalhadaDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAnoTurma.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#112798](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112798)
[AB#111921](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/111921)
> Fix/112798 para Release

- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AtivarUsuarioExterno/AtivarUsuarioExternoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Usuario/ObterUsuarioPorLogin/ObterUsuarioPorLoginQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
[AB#115302](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115302)
> [BACK CONECTA]Logins diferente para o mesmo CPF

- SME.ConectaFormacao.Aplicacao/CasosDeUso/AreaPromotora/CasoDeUsoObterAreaPromotoraLista.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/AreaPromotora/CasoDeUsoObterAreaPromotoraListaAreaPublica.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosPaginadosComFiltros.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaPaginacao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostasDashboard.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraLista/ObterAreaPromotoraListaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraLista/ObterAreaPromotoraListaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterDashBoard/ObterDashBoardQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterDashBoard/ObterDashBoardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaPaginada/ObterPropostaPaginadaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaPaginada/ObterPropostaPaginadaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdDashboard/ObterPropostasIdDashboardQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdDashboard/ObterPropostasIdDashboardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/UsuarioLogado/ObterAreaPromotoraUsuarioLogado/ObterAreaPromotoraUsuarioLogadoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/UsuarioLogado/ObterAreaPromotoraUsuarioLogado/ObterAreaPromotoraUsuarioLogadoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/AreaPromotora/ICasoDeUsoObterAreaPromotoraListaAreaPublica.cs
- SME.ConectaFormacao.Dominio/Constantes/Perfis.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Mocks/UsuarioInserirExternoMock.cs
- SME.ConectaFormacao.Webapi/Controllers/PublicoController.cs
[AB#115313](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115313)
> Feature/115313 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ExisteCargoFuncaoOutrosNaProposta/ExisteCargoFuncaoOutrosNaPropostaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ExisteCargoFuncaoOutrosNaProposta/ExisteCargoFuncaoOutrosNaPropostaQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#115038](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115038)
> validação quando o tipo de inscrição é automática e a função/atividade está selecionada com a opção "Outros"

- SME.ConectaFormacao.Aplicacao/Comandos/AreaPromotora/RemoverAreaPromotora/RemoverAreaPromotoraCommandHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#115304](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115304)
> Fix/115304 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostasDashboard.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaRegente/SalvarPropostaRegenteCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTutor/SalvarPropostaTutorCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarSeJaExisteRegenteTurmaAntesDeCadastrar/ValidarSeJaExisteRegenteTurmaAntesDeCadastrarCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarSeJaExisteRegenteTurmaAntesDeCadastrar/ValidarSeJaExisteRegenteTurmaAntesDeCadastrarCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarSeJaExisteTutorTurmaAntesDeCadastrar/ValidarSeJaExisteTutorTurmaAntesDeCadastrarCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarSeJaExisteTutorTurmaAntesDeCadastrar/ValidarSeJaExisteTutorTurmaAntesDeCadastrarCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ExisteCargoFuncaoOutrosNaProposta/ExisteCargoFuncaoOutrosNaPropostaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ExisteCargoFuncaoOutrosNaProposta/ExisteCargoFuncaoOutrosNaPropostaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasDashboard/ObterPropostasDashboardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdDashboard/ObterPropostasIdDashboardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterTotalDashboardPorTipo/ObterTotalDashboardPorTipoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Usuario/ValidarUsuarioSituacaoAtiva/ValidarUsuarioSituacaoAtivaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/UsuarioExternoDTO.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.Dominio/Extensoes/EnumExtensao.cs
- SME.ConectaFormacao.Infra.Dados/ConectaFormacaoConexao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
- SME.ConectaFormacao.Webapi/Controllers/FuncionarioExternoController.cs
[AB#115325](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115325)
> Fix/115325 para Release

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#112036](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/112036)
> Fix/112036 para Release

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
[AB#114730](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114730)
> Fix/114730 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Formacao/CasoDeUsoObterListagemFormacaoPaginado.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdsPorFiltro/ObterPropostasIdsPorFiltroQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdsPorFiltro/ObterPropostasIdsPorFiltroQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#115338](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115338)
> Fix/115338 para Release

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#115426](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115426) 
[AB#110220](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/110220)
> Feature/115426 para Release

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterUnidadePorCodigoEOL/ObterUnidadePorCodigoEOLQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterUnidadePorCodigoEOL/ObterUnidadePorCodigoEOLQueryHandler.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/UnidadeEol.cs
[AB#114566](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114566)
> Fix/114566 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAlterarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#115671](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115671)
> Validação para nao salvar sem dre

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaRegente/SalvarPropostaRegenteCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTutor/SalvarPropostaTutorCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Dre/ObterDreTodos/ObterDreTodosQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Dre/ObterDreTodos/ObterDreTodosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaRegenteDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTutorDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaRegente.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTutor.cs
- SME.ConectaFormacao.Dominio/Extensoes/StringExtensao.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaRegenteMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTutorMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_regente_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_tutor_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- scripts/V49__ALTERAR_TABELA_REGENTE_TUTOR_ADD_CPF.sql
[AB#115639](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115639)
> Task 115639: Critério3 - Criar campo CPF para regente e tutor

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaInscricaoAutomaticaPorId/ObterPropostaInscricaoAutomaticaPorIdQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/ObjetosDeValor/PropostaInscricaoAutomatica.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#115798](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115798)
> Fix/115798 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaInscricaoAutomaticaPorId/ObterPropostaInscricaoAutomaticaPorIdQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/ObjetosDeValor/PropostaInscricaoAutomatica.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#115798](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115798)
> Fix/115798 para Master

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterInscricaoTipo.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAlterarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoTipoListaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoTipoListaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterInscricaoTipo.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoInscricao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_inscricao_tipo.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#113949](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113949)
> Criar novos tipos de inscrição (Manual e Externa)

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
[AB#115828](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115828)
> Fix/115828 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
> Fix/115628 para Master

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#115794](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115794)
> [MASTER]Não está trocando de página na tela de inscrições

- SME.ConectaFormacao.Webapi/Controllers/ArquivoController.cs
[AB#115822](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115822)
> [Release - BACK] - Não é possível remover o anexo da inscrição

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Servicos/Utilitarios/UtilValidacoes.cs
[AB#115857](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115857)
> [Release] - Cadastro de usuários - Não está validando CPF

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
[AB#116046](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116046)
> Validação CPF Duplicada

- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
[AB#116045](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116045)
> Validação no botão cancelar inscrição

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaRegente/SalvarPropostaRegenteCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTutor/SalvarPropostaTutorCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#115979](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115979)
> Sistema permite incluir o mesmo CPF para a mesma turma para tutores e regentes

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#115834](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115834)
> [Master Back] - Fix/115834

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosInscricao.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
[AB#116317](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116317)
[AB#115832](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115832)
> [Release BACK] - Fix/116317

- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoPaginadaDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
[AB#115830](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115830)
> [MASTER] - Não está permitindo cancelar a inscrição

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAlterarProposta.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoAutomatica/SalvarInscricaoAutomaticaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaRegente/SalvarPropostaRegenteCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTutor/SalvarPropostaTutorCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/CargoFuncao/ObterCargoFuncao/ObterCargoFuncaoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ExisteCargoFuncaoOutrosNaProposta/ExisteCargoFuncaoOutrosNaPropostaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaInscricaoAutomaticaPorId/ObterPropostaInscricaoAutomaticaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdDashboard/ObterPropostasIdDashboardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdsPorFiltro/ObterPropostasIdsPorFiltroQueryHandler.cs
- SME.ConectaFormacao.Dominio/Extensoes/StringExtensao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioCargoFuncao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.Infra.Servicos/Utilitarios/UtilValidacoes.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_tutor_proposta.cs
Adicionado Await em consultas e Cleanup no projeto
> [MASTER ]Adicionado Await em consultas e Cleanup no projeto

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargo/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargo/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/AreaPromotoraMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/ComponenteCurricularMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/InscricaoMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaEncontroMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaEncontroTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaRegenteMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaRegenteTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaDreMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTutorMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTutorTurmaMap.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Constante/EndpointsEolConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/DreUeAtribuicaoServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Interfaces/IServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
[AB#116376](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116376)
> fix/116376 para Release

- scripts/V50__REMOVE_DEPARA_DUPLICADO.sql
[AB#116060](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116060)
> fix/116060 para Master

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
[AB#116254](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116254)
> Remoção de códigos desnecessários

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoParametroSistema.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Ao_inserir_usuario_externo.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Mocks/UsuarioInserirExternoMock.cs
- scripts/V51__ADICIONAR_PARAMETRO_CONFIRMAR_EMAIL_USUARIO_EXTERNO.sql
[AB#116609](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116609)
> Feature/116609 para Story/115944

- SME-ConectaFormacao.sln
- SME.ConectaFormacao.Acessorio/Infra/Dados/Coresso/UsuarioCoressoRepositorio.cs
- SME.ConectaFormacao.Acessorio/Infra/Dados/Eol/FuncionarioEolRepositorio.cs
- SME.ConectaFormacao.Acessorio/Program.cs
- SME.ConectaFormacao.Acessorio/SME.ConectaFormacao.Acessorio.csproj
[AB#116610](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116610)
> Feature/116610 para Story/115944

- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/SalvarUsuario/SalvarUsuarioCommandHandler.cs
[AB#115832](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/115832)
> [BACK RELEASE]Remoção de cache ao atualizar Dados do Usuario

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#116796](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116796)
> Correção da Paginação da Lista de regentes

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoSalvarInscricao.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoSalvarInscricao.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#116324](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116324)
> [BACK] Adicionar informação no endpoint de formação resumida o campo integrarGSA - critério 10

- SME.ConectaFormacao.Aplicacao/Dtos/RetornoFormacaoDetalhadaDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/RetornoListagemFormacaoDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/ObjetosDeValor/FormacaoDetalhada.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#116262](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116262)
> Feature/116262 para story/115944

- SME.ConectaFormacao.Aplicacao/CasosDeUso/AreaPromotora/CasoDeUsoObterAreaPromotoraPorId.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Autentiacao/CasoDeUsoAutenticarAlterarPerfil.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosInscricao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterInformacoesCadastrante.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/PublicarNaFilaRabbit/PublicarNaFilaRabbitCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraCompletaPorId/ObterAreaPromotoraCompletaPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraCompletaPorId/ObterAreaPromotoraCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraPorId/ObterAreaPromotoraPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraPorId/ObterAreaPromotoraPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterInformacoesCadastrante/ObterInformacoesCadastranteQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterInformacoesCadastrante/ObterInformacoesCadastranteQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/UsuarioLogado/ObterUsuarioLogado/ObterUsuarioLogadoQuery.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterInformacoesCadastrante.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_informacoes_cadastrante_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/ServicosFakes/ObterUsuarioLogadoQueryHandlerFaker.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#116277](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116277)
> Feature/116277 para Story/115944

- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/FiltroListagemInscricaoDTO.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
[AB#116263](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116263)
> Feature/116263 para Story/115944

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargo/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargo/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/AreaPromotoraMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/ComponenteCurricularMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/InscricaoMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaEncontroMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaEncontroTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaRegenteMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaRegenteTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaDreMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTutorMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTutorTurmaMap.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Constante/EndpointsEolConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/DreUeAtribuicaoServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Interfaces/IServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
[AB#116376](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116376)
> fix/116376 para Master

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/AtualizarUsuarioServicoAcesso/AtualizarUsuarioServicoAcessoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/AtualizarUsuarioServicoAcesso/AtualizarUsuarioServicoAcessoCommandHandler.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Constante/EndpointsServicoAcessosConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Interfaces/IServicoAcessos.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
[AB#116775](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116775)
> Fix/116775 para Release

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargo/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargo/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/AreaPromotoraMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/ComponenteCurricularMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/InscricaoMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaEncontroMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaEncontroTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaRegenteMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaRegenteTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaDreMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTurmaMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTutorMap.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaTutorTurmaMap.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Constante/EndpointsEolConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/DreUeAtribuicaoServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/Interfaces/IServicoEol.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
[AB#116720](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116720)
> [Release] - Fix/116720

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurma/SalvarPropostaTurmaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurma/SalvarPropostaTurmaCommandHandler.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
[AB#117094](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117094)
> Chamando a fila para gerar as vagas após alteração de quantidade de turmas

- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargo/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#116720](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116720)
> [MASTER] - Fix/116720

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Formacao/CasoDeUsoObterFormacaoDetalhada.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ServicoArmazenamento/ObterEnderecoArquivoServicoArmazenamento/ObterEnderecoArquivoServicoArmazenamentoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
[AB#116585](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116585)
> [BACK MASTER] - Fix/116585

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/AtualizarUsuarioServicoAcesso/AtualizarUsuarioServicoAcessoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/AtualizarUsuarioServicoAcesso/AtualizarUsuarioServicoAcessoCommandHandler.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Constante/EndpointsServicoAcessosConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Interfaces/IServicoAcessos.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
Reverts prefeiturasp/SME-Conecta-Formacao#520
> Revert "Revert "Fix/116775 para Master""

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoUsuarioAlterarUnidadeEol.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarUnidadeEolUsuario/AlterarUnidadeEolUsuarioCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarUnidadeEolUsuario/AlterarUnidadeEolUsuarioCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/UnidadeEolUsuarioDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Usuario/ICasoDeUsoUsuarioAlterarUnidadeEol.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Ao_alterar_unidade_eol_do_usuario.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Mocks/UsuarioAlterarUnidadeEolMock.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioController.cs
[AB#116281](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116281)
> Feature/116281 para Story/116597

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#117253](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117253)
> [Pre Prod] - Mensagem de erro incorreta quando usuário já tem cadastro com RF

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarPublicoAlvoOutros/ValidarPublicoAlvoOutrosCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarPublicoAlvoOutros/ValidarPublicoAlvoOutrosCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/CargoFuncao/ObterCargoFuncao/ObterCargoFuncaoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/CargoFuncao/ObterCargoFuncaoOutros/ObterCargoFuncaoOutrosQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/CargoFuncao/ObterCargoFuncaoOutros/ObterCargoFuncaoOutrosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Dominio/Constantes/CacheDistribuidoNomes.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioCargoFuncao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioCargoFuncao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_gerar_proposta_turma_vaga.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta_paginada.cs
- scripts/V52__ALTERAR_TABELA_PROPOSTA_ADD_PUB_ALVO_OUTROS.sql
[AB#116331](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116331)
> Feature/116331 para Story/116597

- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarUnidadeEolUsuario/AlterarUnidadeEolUsuarioCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Eol/ObterUnidadePorCodigoEOL/ObterUnidadePorCodigoEOLQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterMeusDadosServicoAcessosPorLogin/ObterMeusDadosServicoAcessosPorLoginQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/DadosUsuarioDTO.cs
- SME.ConectaFormacao.Dominio/Constantes/CacheDistribuidoNomes.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/AcessosDadosUsuario.cs
[AB#117334](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117334)
> Alteração de unidade e limpeza de cache

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaEncontro/SalvarPropostaEncontroCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTurmasComVagasPorId/ObterPropostaTurmasComVagasPorIdQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/CacheDistribuidoNomes.cs
[AB#116316](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/116316)
> Feature/116316 para story/116597

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosInscricao.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurma/SalvarPropostaTurmaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurma/SalvarPropostaTurmaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarPublicoAlvoOutros/ValidarPublicoAlvoOutrosCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarSeExisteRegenteTurma/ValidarSeExisteRegenteTurmaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarUnidadeEolUsuario/AlterarUnidadeEolUsuarioCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/SalvarUsuario/SalvarUsuarioCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/DadosListagemInscricaoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoPaginadaDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/UsuarioExternoDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
- SME.ConectaFormacao.Infra.Servicos/Eol/ServicoEol.cs
[AB#117342](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117342)
> Feature/117342 para Story/116597

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterNomeCursistaInscricao.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterNomeCursistaInscricao.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_cursista_inscricao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Mocks/ObterNomeCursistaInscricaoMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/ServicosFakes/ObterNomeProfissionalPorRegistroFuncionalQueryHandlerFaker.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#113950](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113950)
> Feature/113950 para Story/107854

- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
[AB#117536](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117536)
> Ajustas Endpoint  de obter Proposta PorId

- SME.ConectaFormacao.Aplicacao/CasosDeUso/CasoDeUsoAbstratoPaginado.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterArquivosInscricaoImportados.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterArquivosInscricaoImportadosQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterArquivosInscricaoImportadosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/ArquivoInscricaoImportadoDto.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterArquivosInscricaoImportados.cs
- SME.ConectaFormacao.Infra.Dados/Dtos/Inscricao/ArquivosImportadosDto.cs
- SME.ConectaFormacao.Infra.Dados/Dtos/Inscricao/ArquivosInscricaoPaginadoDto.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioImportacaoArquivo.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioImportacaoArquivo.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/ImportacaoArquivo/Ao_realizar_importacao_arquivo.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_arquivos_importacao.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/ImportacaoArquivoMock.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/ImportacaoArquivoRegistroMock.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#113969](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113969)
> 113969 - Criar endpoint para listar os arquivos importados da proposta

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoArquivo/CasoDeUsoInscricaoManualCancelarProcessamento.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ImportacaoArquivo/AlterarSituacaoArquivosParaAguardandoProcessamento/AlterarSituacaoArquivosParaAguardandoProcessamentoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ImportacaoArquivo/AlterarSituacaoArquivosParaCancelado/AlterarSituacaoArquivosParaCanceladoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ImportacaoArquivo/AlterarSituacaoArquivosParaCancelado/AlterarSituacaoArquivosParaCanceladoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/ImportacaoArquivo/ICasoDeUsoInscricaoManualCancelarProcessamento.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/ImportacaoArquivo/Ao_alterar_situacao_arquivo.cs
- SME.ConectaFormacao.Webapi/Controllers/ImportacaoArquivoController.cs
[AB#113972](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113972)
> 113972 - Criar endpoint para cancelar processamento

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAlterarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#117807](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117807)
> back fix-117807

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaDetalhePorId/ObterFormacaoDetalhadaPorIdQueryHandler.cs
[AB#117858](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117858)
> Critério 4.1 - Na área pública a ordenação das turmas não está em ordem alfabética

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTurmasComVagasPorId/ObterPropostaTurmasComVagasPorIdQueryHandler.cs
[AB#117974](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117974)
> Ajustar ordenação e quando tem somente 1 data

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoManual/SalvarInscricaoManualCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoManualDTO.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#118133](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118133)
> [BACK] - A mensagem de alerta não é exibida quando o usuário está cadastrado em outra DRE

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#117253](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117253)
> [Master] - Mensagem de erro incorreta quando usuário já tem cadastro com RF

- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterMeusDadosServicoAcessosPorLogin/ObterMeusDadosServicoAcessosPorLoginQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/DadosUsuarioDTO.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/AcessosDadosUsuario.cs
[AB#118054](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118054)
> Obter e-mail @edu

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoUsuarioAlterarEmailEducacional.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarEmailEducacional/AlterarEmailEducacionalCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarEmailEducacional/AlterarEmailEducacionalCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Usuario/ICasoDeUsoUsuarioAlterarEmailEducacional.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Ao_alterar_email_do_usuario.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Mocks/UsuarioAlterarEmailMock.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioController.cs
[AB#118055](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118055)
> Criado endpoint e testes

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosInscricao.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
[AB#118186](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118186)
>  Critério 7 - Validação do e-mail @edu na inscrição

- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/MontarEmailEducacional/MontarEmailEducacionalCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/MontarEmailEducacional/MontarEmailEducacionalCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/SalvarUsuario/SalvarUsuarioCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterMeusDadosServicoAcessosPorLogin/ObterMeusDadosServicoAcessosPorLoginQueryHandler.cs
[AB#118057](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118057)
> Critério 3 e 4 - Usuário já cadastrados

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterNomeCpfCpfCursistaInscricao.cs
[AB#118304](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118304)
> Não exibe mensagem de erro ao preencher um RF inválido ao clicar na lupa de pesquisa

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoManual/SalvarInscricaoManualCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_realizar_inscricao_manual.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/ServicosFakes/ObterDreUeAtribuicaoPorRegistroFuncionalCodigoCargoQueryHandlerFake.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#118150](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118150)
> 118150 - Está permitindo realizar inscrições em formações fora do período de inscrição

- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#118163](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118163)
> 118163 - Não exibi inconsistência para arquivos invalidos

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterNomeCpfCpfCursistaInscricao.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/SalvarUsuarioParcial/SalvarUsuarioParcialCommandHandler.cs
[AB#118308](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118308)
> 118308 - Removendo cache apos alterar nome

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
[AB#118798](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118798)
> 118798 - Validação incorreta

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoManual/SalvarInscricaoManualCommandHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
[AB#118302](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118302)
> Alterar mensagem de erro

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
[AB#118798](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118798)
> 118798 - Mensagem incorreta

- scripts/V57__ATUALIZAR_EMAIL_EDUCACIONAL.sql
[AB#118966](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118966)
> [PRE-PROD]preencher email @edu

- scripts/V57__ATUALIZAR_EMAIL_EDUCACIONAL.sql
[AB#118966](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118966)
> [MASTER]preencher email @edu

- .gitignore
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/SalvarUsuario/SalvarUsuarioCommandHandler.cs
[AB#119043](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119043)
> [PREPROD] - Erro ao acessar "Meus dados"

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoObterTiposEmail.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Usuario/ICasoDeUsoObterTiposEmail.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoEmail.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/UsuarioMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioController.cs
- scripts/V58__ADICIONAR_TIPO_EMAIL_USUARIO.sql
[AB#119062](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119062)
> Critério 1 - Tipo de usuário

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterInscricaoPorId.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterInscricaoPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/PaginacaoResultadoComMensagemDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterInscricaoPorId.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
[AB#118798](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/118798)
> Retornando propriedades de controle de inscrição não abertas

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/UsuarioExternoDTO.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
[AB#119063](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119063)
> Critério 2 - E-mai Educacional - Back

- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Dominio/SME.ConectaFormacao.Dominio.csproj
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
[AB#119071](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119071)
> Ignorando propriedade na persistência

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoInserirProposta.cs
[AB#119071](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119071)
> Estava engolindo a exceção

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoObterTiposEmail.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Usuario/UsuarioExternoDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Usuario/ICasoDeUsoObterTiposEmail.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoEmail.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/UsuarioMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioController.cs
- scripts/V58__ADICIONAR_TIPO_EMAIL_USUARIO.sql
- scripts/V59__REMOVE_ACENTOS_EMAIL_EDU.sql
[AB#119057](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119057)
> [Master - Back] - Story/119057

- .gitignore
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/SalvarUsuario/SalvarUsuarioCommandHandler.cs
[AB#119043](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119043)
> [MASTER] - Erro ao acessar "Meus dados"

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoProcessarRegistroDoArquivoDeImportacaoInscricao.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoImportacao/SalvarInscricaoImportacaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoImportacao/SalvarInscricaoImportacaoCommandHandler.cs
- SME.ConectaFormacao.Dominio/Enumerados/FormacaoHomologada.cs
[AB#119055](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119055)
> Tratamento de exceções ao processar

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/AlterarCargoFuncaoVinculoInscricao/AlterarCargoFuncaoVinculoInscricaoCommandHandler.cs
[AB#119099](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119099)
> 119099 - Ao editar o cargo deve ser exibido a mensagem de inconsistência

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Usuario/ObterUsuarioPorCpf/ObterUsuarioPorCpfQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Usuario/ObterUsuarioPorCpf/ObterUsuarioPorCpfQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
[AB#117492](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117492)
> Permitiu cadastrar usuário que tem RF

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoManual/SalvarInscricaoManualCommandHandler.cs
[AB#119279](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119279)
[AB#119285](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119285)
> Inscrição Manual salvando origem com valor zero

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
[AB#119288](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119288)
> Adicionado o tipo de origem

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoUsuarioAlterarNome.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarEmailEduAoAlterarNome/AlterarEmailEduAoAlterarNomeCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/AlterarEmailEduAoAlterarNome/AlterarEmailEduAoAlterarNomeCommandHandler.cs
[AB#119311](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119311)
> Ao alterar nome não altera o e-mail @edu

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
[AB#119501](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119501)
> [MASTER] - Quando informado cargo e função não está permitindo inscrição com a fnção

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
[AB#119489](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119489)
> Não é exibido o vínculo na importação do arquivo

- SME.Conecta.Worker.Rabbbit/WorkerRabbitMQ.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoAtualizarCargoFuncaoVinculoInscricaoCursista.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/GerarPropostaTurmaVaga/GerarPropostaTurmaVagaCommandHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.Infra.Servicos/Rabbit/RotasRabbit.cs
[AB#117513](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/117513)
> Turmas criadas após a primeira publicação ficam como inscrições encerradas

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoManual/SalvarInscricaoManualCommandHandler.cs
[AB#119501](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119501)
> [PREPROD] - Validação em Inscrição com e sem Arquivo

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirProposta/InserirPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarResponsavelDf/ValidarResponsavelDfCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/ValidarResponsavelDf/ValidarResponsavelDfCommandHandler.cs
[AB#113235](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113235)
> Adicionada validação do responsável DF ao enviar a proposta.

- scripts/V63__UPDATE_UE_INSCRICAO_INGRESSANTES.sql
[AB#119813](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119813)
> [PROD]Story/119813

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
[AB#113235](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/113235)
> Removida validação não necessária.

- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/MontarEmailEducacional/GerarEmailEducacionalCommandHandler.cs
[AB#120239](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120239)
> [Master]Fix/120239

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoDevolverProposta.cs
[AB#120395](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120395)
> ajustada descrição do e-mail

- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterMeusDadosServicoAcessosPorLogin/ObterMeusDadosServicoAcessosPorLoginQueryHandler.cs
- scripts/V70__UPDATE_CODIGO_UNIDADE_INVALIDO.sql
[AB#120354](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120354)
> [PPREPROD]Ao acessar Meus Dados está exibindo msg: erro ao obter meus dados

- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterMeusDadosServicoAcessosPorLogin/ObterMeusDadosServicoAcessosPorLoginQueryHandler.cs
- scripts/V70__UPDATE_CODIGO_UNIDADE_INVALIDO.sql
[AB#120354](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120354)
> [MASTER]Ao acessar Meus Dados está exibindo msg: erro ao obter meus dados

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/InserirProposta/InserirPropostaCommand.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_inserir_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
[AB#119754](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119754)
> 119754 - Persistir Link para inscrições

- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- scripts/V73__ADICIONAR_CAMPO_CODIGO_EVENTO_TABELA_PROPOSTA.sql
[AB#119759](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119759)
> 119759 - Criando Código do evento na prosposta

- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#119760](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119760)
> 119760 - Persistir Código do evento na proposta

- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaMap.cs
- scripts/V74__ADICIONAR_CAMPO_NUMERO_HOMOLOGACAO_TABELA_PROPOSTA.sql
[AB#119762](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119762)
> 119762 - Criar campo Número de homologação

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Funcionario/CasoDeUsoObterParecerista.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterUsuariosPareceristas/ObterUsuariosPareceristasQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ServicoAcessos/ObterUsuariosPareceristas/ObterUsuariosPareceristasQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Funcionario/UsuarioPareceristaDto.cs
- SME.ConectaFormacao.Aplicacao/Dtos/RetornoUsuriosPareceristasDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Funcionario/ICasoDeUsoObterParecerista.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Constante/EndpointsServicoAcessosConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Interfaces/IServicoAcessos.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/RetornoUsuriosPareceristas.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/FuncionarioController.cs
[AB#114020](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114020)
> Criar endpoint para obter os pareceristas por RF ou Nome

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAlterarProposta.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#119763](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119763)
> 119763 - Persistir o campo Número de homologação

- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaParecerDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaParecer.cs
- SME.ConectaFormacao.Dominio/Enumerados/CampoParecer.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaParecerMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioPropostaParecer.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioPropostaParecer.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- scripts/V75__CRIAR_TABELA_PROPOSTA_PARECERISTA.sql
[AB#114032](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114032)
> [Backend] Criar tabela proposta campo parerer

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta_paginada.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaPaginacaoMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
[AB#119766](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119766)
> 119766 - Filtro na listagem de proposta número homologação

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
[AB#120454](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120454)
> Correção da vlaidação de preenchimento de Dre

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterDadosPaginadosComFiltros.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/FiltroListagemInscricaoComTurmaDTO.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_dados_paginados_com_filtro.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
[AB#119781](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119781)
> 119781 - Filtro na listagem de inscrições por número de homologação na proposta

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommandHandler.cs
[AB#120454](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120454)
> Deverá remover os caches no princípio da alteração - tem fila sendo chamado antes do remover cache final

- scripts/V76__ADICIONAR_OPCAO_CAMPO_CRITERIO_VALIDACAO_NA_PROPOSTA.sql
[AB#119785](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119785)
> 119785 - Inserir critério validação inscrição

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurma/SalvarPropostaTurmaCommandHandler.cs
[AB#120454](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120454)
> Recriar as turmas vagas somente quando for SALVAR final = publicada

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaTurma/SalvarPropostaTurmaCommandHandler.cs
[AB#120454](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120454)
> MASTER --> Fix/120454 

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoRemoverParecerDaProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/Parecer/ExcluirParecerCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/Parecer/ExcluirParecerCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoRemoverParecerDaProposta.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#120667](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120667)
> Excluir Parecer

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterDashBoard/ObterDashBoardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDashboardItemDTO.cs
- SME.ConectaFormacao.Dominio/Entidades/Proposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
[AB#119784](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119784)
> 119784 - Apresentar formações com inscrição externa

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterDashBoard/ObterDashBoardQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDashboardItemDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/RetornoFormacaoDetalhadaDTO.cs
- SME.ConectaFormacao.Dominio/ObjetosDeValor/FormacaoDetalhada.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_formacao_detalhada.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_formacao_listagem.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
[AB#119784](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119784)
> 119784 - Apresentar formações com inscrição externa na área pública

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterPropostaParecer.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoSalvarPropostaParecer.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecer/SalvarPropostaParecerCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecer/SalvarPropostaParecerCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaParecerPorPropostaIdECampo/ObterPropostaParecerPorPropostaIdECampoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaParecerPorPropostaIdECampo/ObterPropostaParecerPorPropostaIdECampoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaParecerCadastroDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaParecerCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaParecerDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaParecerFiltroDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterPropostaParecer.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoSalvarPropostaParecer.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Extensoes/GuidExtension.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioPropostaParecer.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioPropostaParecer.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#114041](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114041)
> [Backend] Criar endpoint para obter os parecer do campo

- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterPerfilAreaPromotora/ObterPerfilAreaPromotoraQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterPerfilAreaPromotora/ObterPerfilAreaPromotoraQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaParecerPorPropostaIdECampo/ObterPropostaParecerPorPropostaIdECampoQueryHandler.cs
[AB#114041](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114041)
> Adicionando query para obter área promotora do perfil

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_parecer_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/TesteBase.cs
[AB#114041](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114041)
> Correção do excluir parecer e testes de cursistas

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaParecerPorPropostaIdECampo/ObterPropostaParecerPorPropostaIdECampoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/Perfis.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_parecer_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaParecerMock.cs
- SME.ConectaFormacao.TesteIntegracao/TesteBase.cs
[AB#114041](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114041)
> Criando os testes de integração para criação do parecer

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPermissaoParecerPerfilLogado/ObterPermissaoParecerPerfilLogadoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPermissaoParecerPerfilLogado/ObterPermissaoParecerPerfilLogadoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTotalParecerDTO.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaTotalParecer.cs
- SME.ConectaFormacao.Dominio/Enumerados/PermissaoTela.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta.cs
[AB#114044](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114044)
> 114044 - trazer o total de parecer por campo e permissão do parecer

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAlterarProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
[AB#114023](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114023)
> 114023 - Alterar situação para Aguardando Análise Parecerista

- SME.ConectaFormacao.Dominio/Entidades/PropostaParecer.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoParecer.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/PropostaParecerMap.cs
- scripts/V75__CRIAR_TABELA_PROPOSTA_PARECER.sql
[AB#114055](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114055)
> Adicionando a situação do parecer

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecerista/SalvarPropostaPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
> Definindo a não obrigatoriedade dos pareceristas e mensagem para o limite de pareceristas permitidos

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarPropostaParecer.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerAdminDF/EnviarParecerAdminDFCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerAdminDF/EnviarParecerAdminDFCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerParecerista/EnviarParecerPareceristaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerParecerista/EnviarParecerPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoEnviarPropostaParecer.cs
- SME.ConectaFormacao.Dominio/Entidades/PropostaParecer.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_enviar_parecer.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#114047](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114047)
> 114047 - Enviar parecer do parecerista

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ExistePareceristasAdicionadosNaProposta/ExistePareceristasAdicionadosNaPropostaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ExistePareceristasAdicionadosNaProposta/ExistePareceristasAdicionadosNaPropostaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
> Somente os pareceristas atribuídos a proposta podem ter acesso ao '+' e somente exibe para Admin DF e Área Promotora quando tiver parecer

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarProposta/SalvarPropostaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecerista/SalvarPropostaPareceristaCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecerista/SalvarPropostaPareceristaCommandHandler.cs
[AB#121093](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121093)
> Corrigindo a alteração de pareceristas

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterTurmasInscricao.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTurmasComVagasPorId/ObterPropostaTurmasComVagasPorIdQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaTurmasComVagasPorId/ObterPropostaTurmasComVagasPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterTurmasInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
Ajuste na funcionalidade de obter turmas através da inscrição incluindo o parâmetro de DRE para filtro dessas turmas.
> Bug: 120678

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostasIdDashboard/ObterPropostasIdDashboardQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
[AB#121087](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121087)
> 121087 - Exibição de propostas para o perfil parecerista

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaPaginada/ObterPropostaPaginadaQueryHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta_paginada.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
[AB#121087](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121087)
> 121087 - Exibição de propostas para o perfil parecerista na tela de prosposta.

- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta.cs
[AB#121172](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121172)
> 121172 - Teste pode enviar

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerAdminDF/EnviarParecerAdminDFCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerParecerista/EnviarParecerPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoParecer.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#121186](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121186)
> Quando parecerista envia e sendo último deve mudar a situação da proposta para 'Aguardando análise do parecer (DF)

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
[AB#121172](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121172)
> Botão enviar deve ficar habilitado quando analise DF

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaParecerPorPropostaIdECampo/ObterPropostaParecerPorPropostaIdECampoQueryHandler.cs
[AB#121186](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121186)
> Quando não tem parecer, deve permitir inserir pareceres

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
[AB#121172](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121172)
> Botão enviar ficará desabilitado e controle será feito via front

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterRelatorioPropostaLaudaPublicacao.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Relatorio/ObterRelatorioProspostaLaudaPublicacao/ObterRelatorioProspostaLaudaPublicacaoHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Relatorio/ObterRelatorioProspostaLaudaPublicacao/ObterRelatorioProspostaLaudaPublicacaoQuery.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterRelatorioPropostaLaudaPublicacao.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/Constantes/EndpointRelatoriosConstants.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/Interfaces/IServicoRelatorio.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/IoC/ServicoRelatorioCHelper.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/Options/RelatorioOptions.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/ServicoRelatorio.cs
- SME.ConectaFormacao.Infra.Servicos/Utilitarios/EnumExtensao.cs
- SME.ConectaFormacao.IoC/Extensions/RegistrarHttpClients.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_relatorio.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/ServicosFakes/ObterRelatorioProspostaLaudaPublicacaoHandlerFaker.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#120076](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120076)
> 120076 - End Point Solicitação Relatório

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/AlterarProposta/AlterarPropostaCommandHandler.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_proposta_parecerista_consideracao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
> Correções dos testes integrados de alteração de proposta

- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaSalvarMock.cs
> Incluir pareceristas nos testes de alteração de proposta

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAprovarProposta.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoRecusarProposta.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaJustificativaDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoAprovarProposta.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoRecusarProposta.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_aprovar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_recusar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Mocks/PropostaJustificativaMock.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#114065](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/114065)
> Feature/114065 para Story/119696

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAprovarProposta.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoRecusarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerAdminDF/EnviarParecerAdminDFCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerParecerista/EnviarParecerPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaTotalConsideracaoDTO.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_aprovar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_enviar_parecer.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_enviar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta_paginada.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_proposta_parecerista_consideracao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_propostas_para_dashboard.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_sugestao_parecer_pareceristas.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_recusar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_proposta_parecerista_consideracao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
[AB#121211](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121211)
> Adequar o retorno de CasoDeUsoObterPropostaPorId - ObterPropostaCompleta

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarPropostaParecer.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerAdminDF/EnviarParecerAdminDFCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerAreaPromotora/EnviarParecerAreaPromotoraCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerAreaPromotora/EnviarParecerAreaPromotoraCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerParecerista/EnviarParecerPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_enviar_parecer.cs
> Correção do Enviar Parecer pelo Parecerista, Admin DF e Área Promotora

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaPareceristaConsideracao/SalvarPropostaPareceristaConsideracaoCommandHandler.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_salvar_proposta_parecerista_consideracao.cs
> Obtendo parecerista por proposta e login

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoEnviarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerParecerista/EnviarParecerPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecerista/SalvarPropostaPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaParecerPorPropostaIdECampo/ObterPropostaParecerPorPropostaIdECampoQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoParecerista.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioPropostaPareceristaConsideracao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioPropostaPareceristaConsideracao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_alterar_proposta.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_enviar_parecer.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_enviar_proposta.cs
[AB#121371](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121371)
> [Backend] C4 - Remover parecerista

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoObterRelatorioPropostaLaudaCompleta.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Relatorio/ObterRelatorioProspostaLaudaCompleta/ObterRelatorioProspostaLaudaCompletaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Relatorio/ObterRelatorioProspostaLaudaCompleta/ObterRelatorioProspostaLaudaCompletaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Proposta/ICasoDeUsoObterRelatorioPropostaLaudaCompleta.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/Constantes/EndpointRelatoriosConstants.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/Interfaces/IServicoRelatorio.cs
- SME.ConectaFormacao.Infra.Servicos/Relatorio/ServicoRelatorio.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_relatorio.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/ServicosFakes/ObterRelatorioProspostaLaudaCompletoHandlerFaker.cs
- SME.ConectaFormacao.Webapi/Controllers/PropostaController.cs
[AB#120038](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/120038)
> 120038 -  End Point Solicitação Relatório

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Usuario/CasoDeUsoInserirUsuarioExterno.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoObterSituacaoUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/Consultas/UsuarioRedeParceria/ObterSituacaoUsuarioRedeParceria/ObterSituacaoUsuarioRedeParceriaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/UsuarioRedeParceria/ObterSituacaoUsuarioRedeParceria/ObterSituacaoUsuarioRedeParceriaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/UsuarioRedeParceria/ICasoDeUsoObterSituacaoUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Usuario/Ao_inserir_usuario_externo.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_obter_situacao_usuario_parceria.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioRedeParceriaController.cs
[AB#119806](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119806)
> Feature/119806 para story/113275

- SME.ConectaFormacao.Dominio/Enumerados/Permissao.cs
[AB#119804](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119804)
> Feature/119804 para Story/113275

- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoObterUsuarioRedeParceriaPaginada.cs
- SME.ConectaFormacao.Aplicacao/Consultas/UsuarioRedeParceria/ObterUsuarioRedeParceiraPaginada/ObterUsuarioRedeParceiraPaginadaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/UsuarioRedeParceria/ObterUsuarioRedeParceiraPaginada/ObterUsuarioRedeParceiraPaginadaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/UsuarioRedeParceria/FiltroUsuarioRedeParceriaDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/UsuarioRedeParceria/UsuarioRedeParceriaPaginadoDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/UsuarioRedeParceria/ICasoDeUsoObterUsuarioRedeParceriaPaginada.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Entidades/Usuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/UsuarioMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_obter_usuario_parceria_paginada.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/UsuarioMock.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioRedeParceriaController.cs
- scripts/V77__ADICIONAR_AREA_PROMOTORA_USUARIO.sql
[AB#119808](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/119808)
> Feature/119808 para Story/113275

- SME.ConectaFormacao.Aplicacao/CasosDeUso/AreaPromotora/CasoDeUsoObterAreaPromotoraListaRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraLista/ObterAreaPromotoraListaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/AreaPromotora/ObterAreaPromotoraLista/ObterAreaPromotoraListaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/AreaPromotora/ICasoDeUsoObterAreaPromotoraListaRedeParceria.cs
- SME.ConectaFormacao.Dominio/Enumerados/AreaPromotoraTipo.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioAreaPromotora.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/AreaPromotora/Ao_obter_lista_area_promotora_rede_parceria.cs
- SME.ConectaFormacao.Webapi/Controllers/AreaPromotoraController.cs
[AB#121796](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121796)
> Feature/121796 para story/113275

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaCompletoDTO.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
[AB#121903](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121903)
> Exibir justificativa relacionada a aprovação e recusa

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecerista/SalvarPropostaPareceristaCommandHandler.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioProposta.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioProposta.cs
[AB#121969](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121969)
> Deverá ignorar os pareceristas desativados

- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoAlterarUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoInserirUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoRemoverUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/DesvincularPerfilExternoCoreSSOServicoAcessos/DesvincularPerfilExternoCoreSSOServicoAcessosCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/DesvincularPerfilExternoCoreSSOServicoAcessos/DesvincularPerfilExternoCoreSSOServicoAcessosCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/InativarUsuarioCoreSSOServicoAcessos/InativarUsuarioCoreSSOServicoAcessosCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/ServicoAcessos/InativarUsuarioCoreSSOServicoAcessos/InativarUsuarioCoreSSOServicoAcessosCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Usuario/UsuarioExisteNoCoreSso/UsuarioExisteNoCoreSsoQuery.cs
- SME.ConectaFormacao.Aplicacao/Dtos/UsuarioRedeParceria/UsuarioRedeParceriaDTO.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Constante/EndpointsServicoAcessosConstantes.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/Interfaces/IServicoAcessos.cs
- SME.ConectaFormacao.Infra.Servicos/Acessos/ServicoAcessos.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_alterar_usuario_parceria.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_inserir_usuario_parceria.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_remover_usuario_parceria.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Mock/UsuarioParceriaMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/ServicosFakes/AtualizarUsuarioServicoAcessoCommandHandlerFaker.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/ServicosFakes/CadastrarUsuarioServicoAcessoCommandHandlerFaker.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/ServicosFakes/DesvincularPerfilExternoCoreSSOServicoAcessosCommandHandlerFaker.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/ServicosFakes/InativarUsuarioCoreSSOServicoAcessosCommandHandlerFaker.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/ServicosFakes/UsuarioExisteNoCoreSsoQueryHandlerFaker.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/ServicosFakes/VincularPerfilExternoCoreSSOServicoAcessosCommandHandlerFaker.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioRedeParceriaController.cs
[AB#121971](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121971)
> Feature/121971 para story/113275

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAlterarProposta.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaDTO.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
[AB#122007](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/122007)
> Quando a área promotora está alterando a proposta, deverá salvar rascunho e as validações serão aplicadas no final (ENVIAR ou SALVAR)

- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/SalvarPropostaParecerista/SalvarPropostaPareceristaCommandHandler.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/Ao_obter_formacao_listagem.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
[AB#122007](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/122007)
> Ao salvar a proposta removendo os pareceristas, não deve fazer o processo de enviar a proposta

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoDTO.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_enviar_inscricao.cs
[AB#121886](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/121886)
> Removendo o campo de e-mail da inscrição

- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoAlterarUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoInserirUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoRemoverUsuarioRedeParceria.cs
- SME.ConectaFormacao.Dominio/Enumerados/TipoUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
[AB#122080](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/122080)
> Fix/122080 para Release

- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoAlterarUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoInserirUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/UsuarioRedeParceria/CasoDeUsoRemoverUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/UsuarioRedeParceria/ICasoDeUsoAlterarUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/UsuarioRedeParceria/ICasoDeUsoInserirUsuarioRedeParceria.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/UsuarioRedeParceria/ICasoDeUsoRemoverUsuarioRedeParceria.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioUsuario.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_alterar_usuario_parceria.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_inserir_usuario_parceria.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/UsuarioRedeParceria/Ao_remover_usuario_parceria.cs
- SME.ConectaFormacao.Webapi/Controllers/UsuarioRedeParceriaController.cs
[AB#122108](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/122108)
> Fix/122108 para Release

- SME.ConectaFormacao.Aplicacao/Comandos/Usuario/SalvarUsuario/SalvarUsuarioCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Autenticacao/ObterTokenAcessoQueryHandler.cs
> Após atualizar o nome, deverá obter as informações do coresso que foram alteradas

- SME-ConectaFormacao.sln
- SME.Conecta.Notificacao.Worker/Hub/NotificacaoHub.cs
- SME.Conecta.Notificacao.Worker/Notificacao/INotificacao.cs
- SME.Conecta.Notificacao.Worker/Notificacao/MensagemNotificacaoDTO.cs
- SME.Conecta.Notificacao.Worker/Notificacao/MensagemNotificacaoGruposDTO.cs
- SME.Conecta.Notificacao.Worker/Notificacao/MensagemNotificacaoUsuariosDTO.cs
- SME.Conecta.Notificacao.Worker/Notificacao/Notificacao.cs
- SME.Conecta.Notificacao.Worker/Notificacao/NotificacaoEventos.cs
- SME.Conecta.Notificacao.Worker/Program.cs
- SME.Conecta.Notificacao.Worker/Properties/launchSettings.json
- SME.Conecta.Notificacao.Worker/SME.Conecta.Notificacao.Worker.csproj
- SME.Conecta.Notificacao.Worker/WorkerRabbitMQNotificacao.cs
- SME.Conecta.Notificacao.Worker/WorkerRabbitMQNotificacaoConstantes.cs
- SME.Conecta.Notificacao.Worker/appsettings.Development.json
- SME.Conecta.Notificacao.Worker/appsettings.json
> Feature/114090 para Story/113239

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Notificacao/CasoDeUsoObterTotalNotificacaoNaoLida.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Notificacao/GerarNotificacao/GerarNotificacaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterTotalNotificacaoNaoLidaPorUsuario/ObterTotalNotificacaoNaoLidaPorUsuarioQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterTotalNotificacaoNaoLidaPorUsuario/ObterTotalNotificacaoNaoLidaPorUsuarioQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoObterTotalNotificacaoNaoLida.cs
- SME.ConectaFormacao.Dominio/Entidades/NotificacaoUsuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/NotificacaoStatus.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/NotificacaoUsuarioMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioNotificacao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioNotificacao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Ao_obter_total_notificacao_nao_lido.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Mocks/AoObterTotalNotificacaoNaoLidoMock.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/ServicosFakes/ObterUsuarioLogadoQueryHandlerFaker.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/NotificacaoMock.cs
- SME.ConectaFormacao.Webapi/Controllers/NotificacaoController.cs
- scripts/V85__CRIAR_TABELA_NOTIFICACAO.sql
> Feature/114087 para story/113239

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Notificacao/CasoDeUsoObterNotificacaoPaginada.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoPaginada/ObterNotificacaoPaginadaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoPaginada/ObterNotificacaoPaginadaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Notificacao/NotificacaoFiltroDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Notificacao/NotificacaoPaginadoDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Notificacao/ICasoDeUsoObterNotificacaoPaginada.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioNotificacao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioNotificacao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Ao_obter_notificacao_paginada.cs
- SME.ConectaFormacao.Webapi/Controllers/NotificacaoController.cs
> Feature/114088 para story/113239

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Notificacao/CasoDeUsoObterCategoriaNotificacao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Notificacao/CasoDeUsoObterSituacaoNotificacao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Notificacao/CasoDeUsoObterTipoNotificacao.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoCategoria/ObterNotificacaoCategoriaQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoCategoria/ObterNotificacaoCategoriaQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoSituacao/ObterNotificacaoSituacaoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoSituacao/ObterNotificacaoSituacaoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoTipo/ObterNotificacaoTipoQuery.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Notificacao/ObterNotificacaoTipo/ObterNotificacaoTipoQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Notificacao/ICasoDeUsoObterCategoriaNotificacao.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Notificacao/ICasoDeUsoObterSituacaoNotificacao.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Notificacao/ICasoDeUsoObterTipoNotificacao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Ao_obter_notificacao_categoria.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Ao_obter_notificacao_situacao.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Ao_obter_notificacao_tipo.cs
- SME.ConectaFormacao.Webapi/Controllers/NotificacaoController.cs
> Feature/122364 para Story/113239

- SME.Conecta.Worker.Rabbbit/WorkerRabbitMQ.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoNotificarResponsavelDFSobreReanaliseDoParecerista.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Notificacao/GerarNotificacaoResponsavelDF/GerarNotificacaoResponsavelDFCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Notificacao/GerarNotificacaoResponsavelDF/GerarNotificacaoResponsavelDFCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Proposta/EnviarParecerParecerista/EnviarParecerPareceristaCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Notificacao/NotificacaoPropostaPareceristaDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/PropostaPareceristaResumidoDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoNotificarResponsavelDFSobreReanaliseDoParecerista.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/NotificacaoUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/NotificacaoUsuarioMap.cs
- SME.ConectaFormacao.Infra.Servicos/Rabbit/RotasRabbit.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Ao_enviar_para_analise_final_responsavel_df.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaPareceristaMock.cs
> [Backend] Enviar notificação para o responsável do DF ao receber sugestão dos pareceristas - critério 5

- SME.Conecta.Worker.Rabbbit/WorkerRabbitMQ.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoAprovarProposta.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoNotificarAreaPromotoraSobreValidacaoFinalPelaDF.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoRecusarProposta.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Notificacao/GerarNotificacaoAreaPromotoraSobreValidacaoFinal/GerarNotificacaoAreaPromotoraSobreValidacaoFinalCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Notificacao/GerarNotificacaoAreaPromotoraSobreValidacaoFinal/GerarNotificacaoAreaPromotoraSobreValidacaoFinalCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoNotificarAreaPromotoraSobreValidacaoFinalPelaDF.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/NotificacaoUsuario.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoProposta.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/NotificacaoUsuarioMap.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioPropostaMovimentacao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioNotificacaoUsuario.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioPropostaMovimentacao.cs
- SME.ConectaFormacao.Infra.Servicos/Rabbit/RotasRabbit.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Notificacao/Ao_enviar_para_area_promotora_sobre_aprovacao_final_pela_df.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMovimentacaoMock.cs
- scripts/V85__CRIAR_TABELA_NOTIFICACAO.sql
> [Backend] Enviar e-mail validação final pelo DF - critério 6

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoConfirmarInscricoes.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/ConfirmarInscricao/ConfirmarInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/ConfirmarInscricao/ConfirmarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricao/SalvarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SalvarInscricaoManual/SalvarInscricaoManualCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/DadosListagemInscricaoDTO.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Proposta/RetornoDTO.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoConfirmarInscricoes.cs
- SME.ConectaFormacao.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Enumerados/SituacaoInscricao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_confirmar_inscricoes.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_inscricoes_por_id_e_filtro.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/InscricaoMock.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/PropostaMock.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
> Feature/119929 para Story/107937

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoEmEsperaInscricoes.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/ConfirmarInscricao/ConfirmarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/EmEsperaInscricao/EmEsperaInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/EmEsperaInscricao/EmEsperaInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoEmEsperaInscricoes.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_colocar_inscricao_em_espera.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
> Feature/119957 para Story/107937

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoCancelarInscricao.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoCancelarInscricoes.cs
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoEncerrarInscricaoAutomaticamenteUsuarios.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/CancelarInscricao/CancelarInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/CancelarInscricao/CancelarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoCancelarInscricoes.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Dominio/Entidades/Inscricao.cs
- SME.ConectaFormacao.Infra.Dados/Mapeamentos/InscricaoMap.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_cancelar_inscricoes.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
- scripts/V86__CRIAR_CAMPO_MOTIVO_CANCELAMENTO_INSCRICAO.sql
> Feature/119958 para story/107937

- SME.ConectaFormacao.Aplicacao/CasosDeUso/ImportacaoInscricao/CasoDeUsoImportacaoInscricaoCursistaValidarItem.cs
- SME.ConectaFormacao.Aplicacao/Consultas/ImportacaoInscricao/ObterInscricoesCursistasPaginado/ObterRegistrosImportacaoInscricaoCursistasPaginadosQueryHandler.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/ImportacaoArquivo/Ao_realizar_importacao_inscricao_manual.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/ImportacaoArquivo/Mocks/ImportacaoArquivoMock.cs
> Feature/119914 para Story/119517

- SME.ConectaFormacao.Aplicacao/Comandos/Email/CancelarIncricao/EnviarEmailCancelarInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Email/CancelarIncricao/EnviarEmailCancelarInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Email/ConfirmacaoInscricao/EnviarEmailConfirmacaoInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/CancelarInscricao/CancelarInscricaoCommandHandler.cs
> E-mail de cancelamento de inscrição

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoObterNomeCpfCpfCursistaInscricao.cs
- SME.ConectaFormacao.Aplicacao/Dtos/RetornoUsuarioCpfNomeDTO.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_obter_cursista_inscricao.cs
> Feature/119909 para story/119517

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoSortearInscricoes.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SortearInscricao/SortearInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/SortearInscricao/SortearInscricaoCommandHandler.cs
- SME.ConectaFormacao.Aplicacao/Consultas/Inscricao/ObterDadosPaginadosComFiltrosQueryHandler.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/DadosListagemFormacaoTurma.cs
- SME.ConectaFormacao.Aplicacao/Interfaces/Inscricao/ICasoDeUsoSortearInscricoes.cs
- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
- SME.ConectaFormacao.Infra.Dados/Dtos/Inscricao/ListagemFormacaoComTurmaDTO.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/Interfaces/IRepositorioInscricao.cs
- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
- SME.ConectaFormacao.IoC/RegistradorDeDependencia.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Inscricao/Ao_realizar_sorteio_inscricoes.cs
- SME.ConectaFormacao.TesteIntegracao/CasosDeUso/Proposta/TestePropostaBase.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/CriterioValidacaoInscricaoMock.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/InscricaoMock.cs
- SME.ConectaFormacao.TesteIntegracao/Mocks/UsuarioMock.cs
- SME.ConectaFormacao.Webapi/Controllers/InscricaoController.cs
> Feature/120012 para story/107938

- SME.ConectaFormacao.Infra.Dados/Repositorios/RepositorioInscricao.cs
> Retornando o arquivo na consulta

- SME.ConectaFormacao.Aplicacao/Comandos/Email/CancelarIncricao/EnviarEmailCancelarInscricaoCommandHandler.cs
> Complementando a mensagem de cancelamento

- SME.ConectaFormacao.Aplicacao/Comandos/Email/ConfirmacaoInscricao/EnviarEmailConfirmacaoInscricaoCommandHandler.cs
> Corrigindo a mensagem para a confirmação

- SME.ConectaFormacao.Aplicacao/Comandos/Inscricao/CancelarInscricao/CancelarInscricaoCommand.cs
- SME.ConectaFormacao.Aplicacao/Dtos/Inscricao/InscricaoMotivoCancelamentoDTO.cs
> Motivo do cancelamento é opcional

- SME.ConectaFormacao.Aplicacao/Comandos/Email/ConfirmacaoInscricao/EnviarEmailConfirmacaoInscricaoCommandHandler.cs
> Corrigindo a informação de data fim

- SME.ConectaFormacao.Dominio/Constantes/MensagemNegocio.cs
> Ajustando a mensagem quando não tem mais vaga

- SME.Conecta.Worker.Rabbbit/wwwroot/ModelosEmail/DevolverProposta.txt
- SME.ConectaFormacao.Aplicacao/CasosDeUso/Proposta/CasoDeUsoDevolverProposta.cs
> 122792 - Ajuste email devolutiva proposta

- SME.ConectaFormacao.Aplicacao/Consultas/Proposta/ObterPropostaCompletaPorId/ObterPropostaCompletaPorIdQueryHandler.cs
> 122793 - Somente pode enviar proposta devolvida caso seja area propotora

- SME.ConectaFormacao.Aplicacao/CasosDeUso/Inscricao/CasoDeUsoRealizarInscricaoAutomatica.cs
[AB#122928](https://dev.azure.com/amcomgov/c82dc1aa-a742-4ea1-8df3-33a7eadb7d70/_workitems/edit/122928)
> 122928 - Ajuste inscrição automatica proposta
